[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./script/inputData" }]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
bsc = { url = "https://bsc.nodereal.io", chain = 56 }
bsc_test = { url = "https://bsc-testnet.bnbchain.org", chain = 97 }

[etherscan]
bsc = { url = "https://api.bscscan.com/api", key = "$BSC_SCAN_API_KEY", chain = 56 }
bsc_test = { url = "https://api-testnet.bscscan.com/api", key = "$BSC_SCAN_API_KEY", chain = 97 }

[profile.chains]
bsc = 56
bsc_test = 97
